options:
  port:
    type: int
    default: 2379
    description: Port to run the public ETCD service on
  management_port:
    type: int
    default: 2380
    description: Port to run the ETCD Management service
  channel:
    type: string
    default: auto
    description: |
      The snap channel from which to install etcd (e.g. '3.3/stable'), or 'auto'
      to accept the charm default. Choosing 'auto' will install the latest 
      supported version of etcd at deploy time, but will not automatically upgrade
      to a newer version thereafter.
  snapd_refresh:
    default: "max"
    type: string
    description: |
      How often snapd handles updates for installed snaps. Set to an empty
      string to check 4x per day. Set to "max" (the default) to check once per
      month based on the charm deployment date. You may also set a custom
      string as described in the 'refresh.timer' section here:
        https://forum.snapcraft.io/t/system-options/87
  bind_to_all_interfaces:
    type: boolean
    default: true
    description: |
      The service binds to all network interfaces if true. The service binds
      only to the first found bind address of each relation if false
  prometheus_datasource:
    default: prometheus
    type: string
    description: |
      Specifies the datasource for Grafana dashboards. This usually corresponds
      to the application name of the related Prometheus. Defaults to
      "prometheus".

      Note: The complete datasource inserted into dashboard will be
      "$prometheus_datasource - Juju generated source"
      This matches how the Prometheus2/Grafana charms format the datasource.